### ISSUE TITLE
Roer pipeline-template plan failing

### ISSUE THREAD

**Issue by loheswaran** [robzienert/tiller#44]
Getting the below error while executing the `roer pipeline-template plan` for a template.  Could you please help me in understanding the root cause of the issue?

**Template :**
Note : Below is not a complete template.
```
schema: "1"
id: APIUIFeatureCDTemplateV1
metadata:
  name: API/UI CD Template
  description: API/UI Continuous Delivery Pipeline Template
  owner: test@test.com
  scopes:
  - global
variables:
- name: variable1
  description: Variable1
- name: variable2
  description: Variable2
configuration:
  concurrentExecutions:
    limitConcurrent: true
    parallel: false
stages:
- id: deploy
  ...
partials: []
```

**Error :**
```
{
  "error": "Bad Request",
  "errors": [
    {
      "message": "unexpected schema version 'null'",
      "severity": "FATAL"
    }
  ],
  "exception": "com.netflix.spinnaker.kork.web.exceptions.ValidationException",
  "message": "Pipeline template is invalid",
  "status": 400,
  "timestamp": "2018-06-26T07:25:40.749+0000"
}
```
