### ISSUE TITLE
pipeline-template publish is removing double quotas around some variable

### ISSUE THREAD

**Issue by oguzdag** [robzienert/tiller#48]
I have a strange problem that I couldn't figure out why.  when using `roer pipeline-template publish`  for publishing a template, it is removing some of double quotas from variables (boolean and integer), and because of this behaviour, deployment fails. let me explain with an example

This is the part of the template file
```
            containers:
              - image: "wurstmeister/kafka:1.1.0"
                name: kafka
                env:
                - name: "KAFKA_AUTO_CREATE_TOPICS_ENABLE"
                  value: "true"
                - name: "KAFKA_BROKER_ID"
                  value: "1"
                - name: "KAFKA_MESSAGE_MAX_BYTES"
                  value: "20000000"
                - name: "KAFKA_ADVERTISED_HOST_NAME"
                  value: "kafka"
                - name: "KAFKA_CREATE_TOPICS"
                  value: "event:1:1"
                - name: "KAFKA_ZOOKEEPER_CONNECT"
                  value: "zookeeper:2181/kafka"
```

This is the publish method
```
roer pipeline-template publish deploy-template.yml
INFO[0000] Publishing template
INFO[0000] Waiting for task to complete...               refURL=/tasks/****
INFO[0002] Pipeline has completed
INFO[0002] Task completed                                status=SUCCEEDED
```

This is the pipeline configuration after publish

```
        containers:
          - env:
              - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
                value: true
              - name: KAFKA_BROKER_ID
                value: 1
              - name: KAFKA_MESSAGE_MAX_BYTES
                value: 20000000
              - name: KAFKA_ADVERTISED_HOST_NAME
                value: kafka
              - name: KAFKA_CREATE_TOPICS
                value: 'event:1:1'
              - name: KAFKA_ZOOKEEPER_CONNECT
                value: 'zookeeper:2181/kafka'
            image: 'wurstmeister/kafka:1.1.0'
```

deployment fails, because publish removes double quotas aroound `true`,`1` and `20000000`

Is there a workaround for publish not to remove double quotas or replace it with single quotas like it does to other variables?
