### ISSUE TITLE
Pipeline doesn't inherit template's 'Configuration' step artefacts and trigger

### ISSUE THREAD

**Issue by dstrychalski** [robzienert/tiller#49]
Pipeline created from a template (both UI or via API) doesn't inherit S3 artefacts and trigger defined in the first 'Configuration' step in the template

**Comment by karlskewes** [comment]
Does your pipeline app config have something like this defined?
```
configuration:
  inherit:
    - expectedArtifacts
    - concurrentExecutions
    - triggers
    - parameters
```

Preceding that section:
```
---
schema: "1"
pipeline:
  application: exampleapp
  id: exampleapp-deploy-to-dev
  name: deploy-to-dev
  owner: you@example.com
  template:
    source: spinnaker://deploy-to-dev-template
```
